apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: my-gateway
#  namespace: fb-test
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 8080
      name: http
      protocol: HTTP
    hosts:
    - 'spring-petclinic.fb-dev.svc.cluster.local'
    - 'hello-world.fb-dev.svc.cluster.local'
