apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-petclinic
#  namespace: fb-test
  labels:
    app: spring-petclinic
    version: v1
spec:
  selector:
    matchLabels:
      app: spring-petclinic
      version: v1
  template:
    metadata:
      labels:
        app: spring-petclinic
        version: v1
      annotations:
        sidecar.istio.io/inject: 'true'
    spec:
      containers:
      - name: spring-petclinic
#        image: 172.30.1.1:5000/demo/spring-petclinic:latest
        image: quay.io/service-binding/spring-petclinic:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: spring-petclinic
spec:
  selector:
    app: spring-petclinic
  ports:
  - name: http
    protocol: TCP
    port: 8080
    targetPort: 8080