apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: spring-petclinic
  namespace: fb-test
spec:
  hosts:
    - 'petclinic-fb-test.apps-crc.testing'
  gateways:
    - my-gateway
  http:
    - route:
        - destination:
            host: spring-petclinic
            port:
              number: 8080