apiVersion: v1
kind: ConfigMap
metadata:
  name: ratelimit-config-test
data:
  config.yaml: |
    domain: productpage-ratelimit-test
    descriptors:
      - key: PATH
        value: "/"
        rate_limit:
          unit: minute
          requests_per_unit: 10
      - key: PATH
        rate_limit:
          unit: minute
          requests_per_unit: 10
