apiVersion: apps/v1
kind: Deployment
metadata:
 labels:
   app.kubernetes.io/name: hello-world
 name: hello-world
 namespace: fb-test
spec:
 replicas: 1
 selector:
   matchLabels:
     app.kubernetes.io/name: hello-world
 template:
   metadata:
     labels:
       app.kubernetes.io/name: hello-world
       sidecar.istio.io/inject: 'true'
       app: hello-world
       version: v1
   spec:
     containers:
     - image: gcr.io/google-samples/hello-app:2.0
       name: hello-world
       ports:
       - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: hello-world
  name: hello-world
  namespace: fb-test
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app.kubernetes.io/name: hello-world
  type: NodePort
status:
  loadBalancer: {}
