apiVersion: route.openshift.io/v1	
kind: Route	
metadata:	
  annotations:	
    openshift.io/host.generated: 'true'	
  labels:	
    app.kubernetes.io/instance: hello-world	
    app.kubernetes.io/name: hello-world-example	
  managedFields:	
    - apiVersion: route.openshift.io/v1	
      fieldsType: FieldsV1	
      fieldsV1:	
        'f:metadata':	
          'f:labels':	
            .: {}	
            'f:app.kubernetes.io/instance': {}	
            'f:app.kubernetes.io/name': {}	
        'f:spec':	
          'f:port':	
            .: {}	
            'f:targetPort': {}	
          'f:to':	
            'f:kind': {}	
            'f:name': {}	
            'f:weight': {}	
          'f:wildcardPolicy': {}	
      manager: Mozilla	
      operation: Update	
      time: '2022-12-06T09:59:03Z'	
    - apiVersion: route.openshift.io/v1	
      fieldsType: FieldsV1	
      fieldsV1:	
        'f:status':	
          'f:ingress': {}	
      manager: openshift-router	
      operation: Update	
      subresource: status	
      time: '2022-12-06T09:59:03Z'	
  name: hello-world	
  namespace: test	
  resourceVersion: '25068593'	
  uid: 4e45c127-b370-4908-ab43-e2e1fb78712f	
spec:	
  host: hello-world-test.apps.ot.gn2.visma.rijksapps.nl	
  port:	
    targetPort: 8080	
  to:	
    kind: Service	
    name: hello-world	
    weight: 100	
  wildcardPolicy: None
