kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: hello-world
  namespace: test
  labels:
    app.kubernetes.io/instance: hello-world
    app.kubernetes.io/name: hello-world
spec:
  host: hello-world-test.apps.ot.gn2.visma.rijksapps.nl
  to:
    kind: Service
    name: hello-world
    weight: 100
  port:
    targetPort: 8080
  wildcardPolicy: None
